data:
  redis:
    host: prod-redis-host
    port: 6379
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
logging:
  level:
    root: WARN
jpa:
  hibernate:
    ddl-auto: validate
  show-sql: false

