# application-DB.yml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/2024_10_ASTRONEER_TEAMPROJECT
    hikari:
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver