spring:
#  devtools:
#    restart:
#      enabled: false
  application:
    name: star_info_web
  config:
    import: classpath:application-DB.properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: "/**"
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000  # ?? ????(???)
      lettuce:
        pool:
          max-active: 8   # ?? ?? ?
          max-idle: 8     # ?? ?? ?? ?
          min-idle: 0     # ?? ?? ?? ?
server:
  port: 7777
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        security.oauth2: DEBUG
        security.web.authentication: DEBUG
        data:
          redis: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    io:
      lettuce:
        core: DEBUG