spring:
  profiles:
    active: prod
    include: secret, DB
  application:
    name: star_info_web
#    base-url: "http://localhost:8080"
    base-url: "https://www.astro.qyef.site"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: "/**"
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 7777
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    com.teamname.astroneer.star_info_web: DEBUG  # 여기는 개발 단계에서 DEBUG로 유지
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: OFF  # 필요할 때만 DEBUG로 바꿀 것을 추천

custom:
  dev:
    cookieDomain: localhost
  prod:
    cookieDomain: www.astro.qyef.site/
    url: "https://${custom.prod.cookieDomain}"