spring:
  profiles:
    active: dev
  application:
    name: star_info_web
  config:
    import:
      - classpath:application-DB.yml
      - classpath:application-secret.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: "/**"
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 7777
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    com.teamname.astroneer.star_info_web: DEBUG
    org:
      springframework:
        security: WARN
        web: INFO
        security.oauth2: WARN
        security.web.authentication: WARN
        org.springframework.security: DEBUG
        data:
          redis: WARN
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: OFF
    io:
      lettuce:
        core: WARN
